"""Render a Louie markdown report into a branded PDF (Chromium/Playwright).

Usage:
  python render_pdf.py "<input.md>" ["<output.pdf>"]

Generic for any Livy report. markdown (tables) -> styled HTML -> PDF.
Severity emoji become coloured dots.
"""
import sys
import re
from pathlib import Path
import markdown
from playwright.sync_api import sync_playwright

CSS = """
* { box-sizing: border-box; }
body { font-family: "Segoe UI", Helvetica, Arial, sans-serif; font-size: 10px;
  color: #222; line-height: 1.45; margin: 0; }
h1 { color: #C8102E; font-size: 21px; margin: 0 0 2px 0; letter-spacing: -.3px; }
h1 + p { color: #555; font-size: 9.5px; margin: 0 0 10px 0; }
h2 { font-size: 12.5px; color: #111; margin: 16px 0 6px 0; padding-bottom: 3px;
  border-bottom: 2px solid #C8102E; }
p { margin: 4px 0; }
strong { color: #111; }
hr { border: none; border-top: 1px solid #e3e3e3; margin: 12px 0; }
table { width: 100%; border-collapse: collapse; margin: 6px 0 10px 0; font-size: 9px;
  page-break-inside: auto; }
tr { page-break-inside: avoid; }
th { background: #1f1f1f; color: #fff; text-align: left; padding: 5px 7px;
  font-weight: 600; border: 1px solid #1f1f1f; }
td { padding: 4px 7px; border: 1px solid #e0e0e0; vertical-align: top; }
tbody tr:nth-child(even) { background: #f7f7f7; }
.alerts table th { background: #C8102E; border-color: #C8102E; }
.alerts table { font-size: 9.5px; }
h2 { page-break-after: avoid; }
.dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%;
  vertical-align: middle; }
.dot.red { background: #C8102E; }
.dot.amber { background: #E8820C; }
.dot.yellow { background: #D9B400; }
.warn { color: #C8102E; font-weight: 700; }
.brandbar { height: 5px; background: #C8102E; margin: 0 0 10px 0; }
"""

def main():
    if len(sys.argv) < 2:
        print('usage: python render_pdf.py "<input.md>" ["<output.pdf>"]')
        sys.exit(1)
    src = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else src.with_suffix(".pdf")
    text = src.read_text(encoding="utf-8")

    text = text.replace("🔴", '<span class="dot red"></span>')
    text = text.replace("🟠", '<span class="dot amber"></span>')
    text = text.replace("🟡", '<span class="dot yellow"></span>')
    text = text.replace("🚨", "").replace("⚠️", '<span class="warn">!</span>')

    body = markdown.markdown(text, extensions=["tables", "sane_lists", "attr_list"])

    # wrap the alerts table so it gets the red header treatment
    m = re.search(r'(Alerts[^<]*</h2>\s*)(<table>)', body)
    if m:
        start = m.end(1)
        end = body.index("</table>", start) + len("</table>")
        body = body[:start] + '<div class="alerts">' + body[start:end] + "</div>" + body[end:]

    html = f'<!doctype html><html><head><meta charset="utf-8"><style>{CSS}</style></head>' \
           f'<body><div class="brandbar"></div>{body}</body></html>'

    footer = ('<div style="font-size:8px;color:#999;width:100%;text-align:right;'
              'padding:0 12mm;">Generated by Louie &middot; multi-company reporting '
              '&middot; page <span class="pageNumber"></span>/'
              '<span class="totalPages"></span></div>')

    with sync_playwright() as p:
        b = p.chromium.launch()
        pg = b.new_page()
        pg.set_content(html, wait_until="networkidle")
        pg.pdf(path=str(out), format="A4", print_background=True,
               display_header_footer=True, header_template="<div></div>",
               footer_template=footer,
               margin={"top": "12mm", "bottom": "16mm", "left": "12mm", "right": "12mm"})
        b.close()
    print("PDF ->", out)

if __name__ == "__main__":
    main()
